' Do not edit this file manually it is auto-generated during the build based on the .resx file for this project.
Imports System.Resources
Imports Community.VisualBasic.CompilerServices

Namespace Global.Community.VisualBasic

  Partial Public Class SR

    'Private Const s_resourcesName As String = "Microsoft.VisualBasic.resources" ' assembly Name + .resources

    Private Shared s_resourceManager As Global.System.Resources.ResourceManager
    Friend Shared ApplicationLogNumberTooSmall As String
    Friend Shared ApplicationLog_ExhaustedPossibleStreamNames As String

    Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
      Get
        If s_resourceManager Is Nothing Then
          's_resourceManager = New Global.System.Resources.ResourceManager(GetType(FxResources.Microsoft.VisualBasic.Core.SR))
          's_resourceManager = New Global.System.Resources.ResourceManager(GetType(Community.VisualBasic.SR))
          s_resourceManager = New Global.System.Resources.ResourceManager("Community.VisualBasic.Resources", GetType(Community.VisualBasic.SR).Assembly)
        End If
        Return s_resourceManager
      End Get
    End Property

    Friend Shared Function Mouse_NoMouseIsPresent() As String
      Throw New NotImplementedException()
    End Function

    ' This method is used to decide if we need to append the exception message parameters to the message when calling SR.Format. 
    ' by default it returns false.
    ' Native code generators can replace the value this returns based on user input at the time of native code generation.
    ' Marked as NoInlining because if this is used in an AoT compiled app that is not compiled into a single file, the user
    ' could compile each module with a different setting for this. We want to make sure there's a consistent behavior
    ' that doesn't depend on which native module this method got inlined into.
    <Global.System.Runtime.CompilerServices.MethodImpl(Global.System.Runtime.CompilerServices.MethodImplOptions.NoInlining)>
    Public Shared Function UsingResourceKeys() As Boolean
      Return False
    End Function

    Friend Shared Function GetResourceString(resourceKey As String,
                                             Optional defaultString As String = Nothing) As String

      If (UsingResourceKeys()) Then
        Return If(defaultString, resourceKey)
      End If

      Dim resourceString As String = Nothing
      Try
        resourceString = ResourceManager.GetString(resourceKey)
      Catch ex As MissingManifestResourceException
      End Try

      ' if we are running on desktop, ResourceManager.GetString will just return resourceKey. so
      ' in this case we'll return defaultString (if it is not null) 
      If defaultString IsNot Nothing AndAlso resourceKey.Equals(resourceString, StringComparison.Ordinal) Then
        Return defaultString
      End If

      'If resourceString Is Nothing Then
      '  Return "MISSING"
      'End If

      Return resourceString

    End Function

    Friend Shared Function Format(ByVal resourceFormat As String, ParamArray args() As Object) As String
      If args IsNot Nothing Then
        If (UsingResourceKeys()) Then
          Return resourceFormat + String.Join(", ", args)
        End If
        Return String.Format(resourceFormat, args)
      End If
      Return resourceFormat
    End Function

    <Global.System.Runtime.CompilerServices.MethodImpl(Global.System.Runtime.CompilerServices.MethodImplOptions.NoInlining)>
    Public Shared Function Format(ByVal resourceFormat As String, p1 As Object) As String
      If (UsingResourceKeys()) Then
        Return String.Join(", ", resourceFormat, p1)
      End If

      Return String.Format(resourceFormat, p1)
    End Function

    <Global.System.Runtime.CompilerServices.MethodImpl(Global.System.Runtime.CompilerServices.MethodImplOptions.NoInlining)>
    Friend Shared Function Format(resourceFormat As String, p1 As Object, p2 As Object) As String
      Try
        If (UsingResourceKeys()) Then
          Return String.Join(", ", resourceFormat, p1, p2)
        End If
        If resourceFormat Is Nothing Then
          resourceFormat = "RESOURCE FORMAT MISSING '{0}' '{1}'"
        End If
        Return String.Format(resourceFormat, p1, p2)
      Catch ex As FormatException
        Throw New Exception($"'{resourceFormat}','{p1}','{p2}'", ex)
      End Try
    End Function

    <Global.System.Runtime.CompilerServices.MethodImpl(Global.System.Runtime.CompilerServices.MethodImplOptions.NoInlining)>
    Friend Shared Function Format(ByVal resourceFormat As String, p1 As Object, p2 As Object, p3 As Object) As String
      If (UsingResourceKeys()) Then
        Return String.Join(", ", resourceFormat, p1, p2, p3)
      End If
      Return String.Format(resourceFormat, p1, p2, p3)
    End Function

    Friend Shared ReadOnly Property ApplicationLogBaseNameNull() As String
      Get
        Return SR.GetResourceString("ApplicationLogBaseNameNull", Nothing)
      End Get
    End Property

    Friend Shared ReadOnly Property EnvVarNotFound_Name() As String
      Get
        Return SR.GetResourceString("EnvVarNotFound_Name", Nothing)
      End Get
    End Property

    Friend Shared ReadOnly Property Array_RankMismatch As String
      Get
        Return SR.GetResourceString("Array_RankMismatch", Nothing)
      End Get
    End Property
    Friend Shared ReadOnly Property Array_TypeMismatch As String
      Get
        Return SR.GetResourceString("Array_TypeMismatch", Nothing)
      End Get
    End Property

    Friend Shared ReadOnly Property ApplicationLog_NegativeNumber() As String
      Get
        Return SR.GetResourceString("ApplicationLog_NegativeNumber", Nothing)
      End Get
    End Property

    Friend Shared ReadOnly Property Network_BadConnectionTimeout() As String
      Get
        Return SR.GetResourceString("Network_BadConnectionTimeout", Nothing)
      End Get
    End Property

    ''' <summary>This Error number is obsolete and no longer used.</summary>
    Friend Shared ReadOnly Property [ID3] As String
      Get
        Return GetResourceString("ID3", "This Error number is obsolete and no longer used.")
      End Get
    End Property
    ''' <summary>Procedure call or argument is not valid.</summary>
    Friend Shared ReadOnly Property [ID5] As String
      Get
        Return GetResourceString("ID5", "Procedure call or argument is not valid.")
      End Get
    End Property
    ''' <summary>Overflow.</summary>
    Friend Shared ReadOnly Property [ID6] As String
      Get
        Return GetResourceString("ID6", "Overflow.")
      End Get
    End Property
    ''' <summary>Out of memory.</summary>
    Friend Shared ReadOnly Property [ID7] As String
      Get
        Return GetResourceString("ID7", "Out of memory.")
      End Get
    End Property
    ''' <summary>Subscript out of range.</summary>
    Friend Shared ReadOnly Property [ID9] As String
      Get
        Return GetResourceString("ID9", "Subscript out of range.")
      End Get
    End Property
    ''' <summary>This array is fixed or temporarily locked.</summary>
    Friend Shared ReadOnly Property [ID10] As String
      Get
        Return GetResourceString("ID10", "This array is fixed or temporarily locked.")
      End Get
    End Property
    ''' <summary>Division by zero.</summary>
    Friend Shared ReadOnly Property [ID11] As String
      Get
        Return GetResourceString("ID11", "Division by zero.")
      End Get
    End Property
    ''' <summary>Type mismatch.</summary>
    Friend Shared ReadOnly Property [ID13] As String
      Get
        Return GetResourceString("ID13", "Type mismatch.")
      End Get
    End Property
    ''' <summary>Out of string space.</summary>
    Friend Shared ReadOnly Property [ID14] As String
      Get
        Return GetResourceString("ID14", "Out of string space.")
      End Get
    End Property
    ''' <summary>Expression too complex.</summary>
    Friend Shared ReadOnly Property [ID16] As String
      Get
        Return GetResourceString("ID16", "Expression too complex.")
      End Get
    End Property
    ''' <summary>Can't perform requested operation.</summary>
    Friend Shared ReadOnly Property [ID17] As String
      Get
        Return GetResourceString("ID17", "Can't perform requested operation.")
      End Get
    End Property
    ''' <summary>User interrupt occurred.</summary>
    Friend Shared ReadOnly Property [ID18] As String
      Get
        Return GetResourceString("ID18", "User interrupt occurred.")
      End Get
    End Property
    ''' <summary>Resume without error.</summary>
    Friend Shared ReadOnly Property [ID20] As String
      Get
        Return GetResourceString("ID20", "Resume without error.")
      End Get
    End Property
    ''' <summary>Out of stack space.</summary>
    Friend Shared ReadOnly Property [ID28] As String
      Get
        Return GetResourceString("ID28", "Out of stack space.")
      End Get
    End Property
    ''' <summary>Sub or Function not defined.</summary>
    Friend Shared ReadOnly Property [ID35] As String
      Get
        Return GetResourceString("ID35", "Sub or Function not defined.")
      End Get
    End Property
    ''' <summary>Too many DLL application clients.</summary>
    Friend Shared ReadOnly Property [ID47] As String
      Get
        Return GetResourceString("ID47", "Too many DLL application clients.")
      End Get
    End Property
    ''' <summary>Error in loading DLL.</summary>
    Friend Shared ReadOnly Property [ID48] As String
      Get
        Return GetResourceString("ID48", "Error in loading DLL.")
      End Get
    End Property
    ''' <summary>Bad DLL calling convention.</summary>
    Friend Shared ReadOnly Property [ID49] As String
      Get
        Return GetResourceString("ID49", "Bad DLL calling convention.")
      End Get
    End Property
    ''' <summary>Internal error.</summary>
    Friend Shared ReadOnly Property [ID51] As String
      Get
        Return GetResourceString("ID51", "Internal error.")
      End Get
    End Property
    ''' <summary>Bad file name or number.</summary>
    Friend Shared ReadOnly Property [ID52] As String
      Get
        Return GetResourceString("ID52", "Bad file name or number.")
      End Get
    End Property
    ''' <summary>File not found.</summary>
    Friend Shared ReadOnly Property [ID53] As String
      Get
        Return GetResourceString("ID53", "File not found.")
      End Get
    End Property
    ''' <summary>Bad file mode.</summary>
    Friend Shared ReadOnly Property [ID54] As String
      Get
        Return GetResourceString("ID54", "Bad file mode.")
      End Get
    End Property
    ''' <summary>File already open.</summary>
    Friend Shared ReadOnly Property [ID55] As String
      Get
        Return GetResourceString("ID55", "File already open.")
      End Get
    End Property
    ''' <summary>Device I/O error.</summary>
    Friend Shared ReadOnly Property [ID57] As String
      Get
        Return GetResourceString("ID57", "Device I/O error.")
      End Get
    End Property
    ''' <summary>File already exists.</summary>
    Friend Shared ReadOnly Property [ID58] As String
      Get
        Return GetResourceString("ID58", "File already exists.")
      End Get
    End Property
    ''' <summary>Bad record length.</summary>
    Friend Shared ReadOnly Property [ID59] As String
      Get
        Return GetResourceString("ID59", "Bad record length.")
      End Get
    End Property
    ''' <summary>Disk full.</summary>
    Friend Shared ReadOnly Property [ID61] As String
      Get
        Return GetResourceString("ID61", "Disk full.")
      End Get
    End Property
    ''' <summary>Input past end of file.</summary>
    Friend Shared ReadOnly Property [ID62] As String
      Get
        Return GetResourceString("ID62", "Input past end of file.")
      End Get
    End Property
    ''' <summary>Bad record number.</summary>
    Friend Shared ReadOnly Property [ID63] As String
      Get
        Return GetResourceString("ID63", "Bad record number.")
      End Get
    End Property
    ''' <summary>Too many files.</summary>
    Friend Shared ReadOnly Property [ID67] As String
      Get
        Return GetResourceString("ID67", "Too many files.")
      End Get
    End Property
    ''' <summary>Device unavailable.</summary>
    Friend Shared ReadOnly Property [ID68] As String
      Get
        Return GetResourceString("ID68", "Device unavailable.")
      End Get
    End Property
    ''' <summary>Permission denied.</summary>
    Friend Shared ReadOnly Property [ID70] As String
      Get
        Return GetResourceString("ID70", "Permission denied.")
      End Get
    End Property
    ''' <summary>Disk not ready.</summary>
    Friend Shared ReadOnly Property [ID71] As String
      Get
        Return GetResourceString("ID71", "Disk not ready.")
      End Get
    End Property
    ''' <summary>Cannot rename with different drive.</summary>
    Friend Shared ReadOnly Property [ID74] As String
      Get
        Return GetResourceString("ID74", "Cannot rename with different drive.")
      End Get
    End Property
    ''' <summary>Path/File access error.</summary>
    Friend Shared ReadOnly Property [ID75] As String
      Get
        Return GetResourceString("ID75", "Path/File access error.")
      End Get
    End Property
    ''' <summary>Path not found.</summary>
    Friend Shared ReadOnly Property [ID76] As String
      Get
        Return GetResourceString("ID76", "Path not found.")
      End Get
    End Property
    ''' <summary>Object variable or With block variable not set.</summary>
    Friend Shared ReadOnly Property [ID91] As String
      Get
        Return GetResourceString("ID91", "Object variable or With block variable not set.")
      End Get
    End Property
    ''' <summary>For loop not initialized.</summary>
    Friend Shared ReadOnly Property [ID92] As String
      Get
        Return GetResourceString("ID92", "For loop not initialized.")
      End Get
    End Property
    ''' <summary>Pattern string is not valid.</summary>
    Friend Shared ReadOnly Property [ID93] As String
      Get
        Return GetResourceString("ID93", "Pattern string is not valid.")
      End Get
    End Property
    ''' <summary>This Error number is obsolete and no longer used.</summary>
    Friend Shared ReadOnly Property [ID94] As String
      Get
        Return GetResourceString("ID94", "This Error number is obsolete and no longer used.")
      End Get
    End Property
    ''' <summary>Application-defined or object-defined error.</summary>
    Friend Shared ReadOnly Property [ID95] As String
      Get
        Return GetResourceString("ID95", "Application-defined or object-defined error.")
      End Get
    End Property
    ''' <summary>Unable to sink events of object because the object is already firing events to the maximum number of event receivers that it supports.</summary>
    Friend Shared ReadOnly Property [ID96] As String
      Get
        Return GetResourceString("ID96", "Unable to sink events of object because the object is already firing events to the maximum number of event receivers that it supports.")
      End Get
    End Property
    ''' <summary>Cannot call friend function on object that is not an instance of defining class.</summary>
    Friend Shared ReadOnly Property [ID97] As String
      Get
        Return GetResourceString("ID97", "Cannot call friend function on object that is not an instance of defining class.")
      End Get
    End Property
    ''' <summary>A property or method call cannot include a reference to a private object, either as an argument or as a return value.</summary>
    Friend Shared ReadOnly Property [ID98] As String
      Get
        Return GetResourceString("ID98", "A property or method call cannot include a reference to a private object, either as an argument or as a return value.")
      End Get
    End Property
    ''' <summary>Class '{0}' does not implement the System.Collections.ICollection interface.</summary>
    Friend Shared ReadOnly Property [ID100] As String
      Get
        Return GetResourceString("ID100", "Class '{0}' does not implement the System.Collections.ICollection interface.")
      End Get
    End Property
    ''' <summary>File format is not valid.</summary>
    Friend Shared ReadOnly Property [ID321] As String
      Get
        Return GetResourceString("ID321", "File format is not valid.")
      End Get
    End Property
    ''' <summary>Cannot create necessary temporary file.</summary>
    Friend Shared ReadOnly Property [ID322] As String
      Get
        Return GetResourceString("ID322", "Cannot create necessary temporary file.")
      End Get
    End Property
    ''' <summary>Format in resource file is not valid.</summary>
    Friend Shared ReadOnly Property [ID325] As String
      Get
        Return GetResourceString("ID325", "Format in resource file is not valid.")
      End Get
    End Property
    ''' <summary>Property value is not valid.</summary>
    Friend Shared ReadOnly Property [ID380] As String
      Get
        Return GetResourceString("ID380", "Property value is not valid.")
      End Get
    End Property
    ''' <summary>Property array index is not valid.</summary>
    Friend Shared ReadOnly Property [ID381] As String
      Get
        Return GetResourceString("ID381", "Property array index is not valid.")
      End Get
    End Property
    ''' <summary>Set not supported at runtime.</summary>
    Friend Shared ReadOnly Property [ID382] As String
      Get
        Return GetResourceString("ID382", "Set not supported at runtime.")
      End Get
    End Property
    ''' <summary>Set not supported (read-only property).</summary>
    Friend Shared ReadOnly Property [ID383] As String
      Get
        Return GetResourceString("ID383", "Set not supported (read-only property).")
      End Get
    End Property
    ''' <summary>Need property array index.</summary>
    Friend Shared ReadOnly Property [ID385] As String
      Get
        Return GetResourceString("ID385", "Need property array index.")
      End Get
    End Property
    ''' <summary>Set not permitted.</summary>
    Friend Shared ReadOnly Property [ID387] As String
      Get
        Return GetResourceString("ID387", "Set not permitted.")
      End Get
    End Property
    ''' <summary>Get not supported at runtime.</summary>
    Friend Shared ReadOnly Property [ID393] As String
      Get
        Return GetResourceString("ID393", "Get not supported at runtime.")
      End Get
    End Property
    ''' <summary>Get not supported (write-only property).</summary>
    Friend Shared ReadOnly Property [ID394] As String
      Get
        Return GetResourceString("ID394", "Get not supported (write-only property).")
      End Get
    End Property
    ''' <summary>Property not found.</summary>
    Friend Shared ReadOnly Property [ID422] As String
      Get
        Return GetResourceString("ID422", "Property not found.")
      End Get
    End Property
    ''' <summary>Property or method not found.</summary>
    Friend Shared ReadOnly Property [ID423] As String
      Get
        Return GetResourceString("ID423", "Property or method not found.")
      End Get
    End Property
    ''' <summary>Object required.</summary>
    Friend Shared ReadOnly Property [ID424] As String
      Get
        Return GetResourceString("ID424", "Object required.")
      End Get
    End Property
    ''' <summary>Cannot create ActiveX component.</summary>
    Friend Shared ReadOnly Property [ID429] As String
      Get
        Return GetResourceString("ID429", "Cannot create ActiveX component.")
      End Get
    End Property

    Friend Shared Function ProgressDialogDownloadingTitle() As String
      Throw New NotImplementedException()
    End Function

    Friend Shared Function ProgressDialogDownloadingLabel() As String
      Throw New NotImplementedException()
    End Function

    ''' <summary>Class does not support Automation or does not support expected interface.</summary>
    Friend Shared ReadOnly Property [ID430] As String
      Get
        Return GetResourceString("ID430", "Class does not support Automation or does not support expected interface.")
      End Get
    End Property
    ''' <summary>File name or class name not found during Automation operation.</summary>
    Friend Shared ReadOnly Property [ID432] As String
      Get
        Return GetResourceString("ID432", "File name or class name not found during Automation operation.")
      End Get
    End Property
    ''' <summary>Object does not support this property or method.</summary>
    Friend Shared ReadOnly Property [ID438] As String
      Get
        Return GetResourceString("ID438", "Object does not support this property or method.")
      End Get
    End Property
    ''' <summary>Automation error.</summary>
    Friend Shared ReadOnly Property [ID440] As String
      Get
        Return GetResourceString("ID440", "Automation error.")
      End Get
    End Property
    ''' <summary>Connection to type library or object library for remote process has been lost. Press OK for dialog to remove reference.</summary>
    Friend Shared ReadOnly Property [ID442] As String
      Get
        Return GetResourceString("ID442", "Connection to type library or object library for remote process has been lost. Press OK for dialog to remove reference.")
      End Get
    End Property
    ''' <summary>Automation object does not have a default value.</summary>
    Friend Shared ReadOnly Property [ID443] As String
      Get
        Return GetResourceString("ID443", "Automation object does not have a default value.")
      End Get
    End Property
    ''' <summary>Object does not support this action.</summary>
    Friend Shared ReadOnly Property [ID445] As String
      Get
        Return GetResourceString("ID445", "Object does not support this action.")
      End Get
    End Property
    ''' <summary>Object does not support named arguments.</summary>
    Friend Shared ReadOnly Property [ID446] As String
      Get
        Return GetResourceString("ID446", "Object does not support named arguments.")
      End Get
    End Property
    ''' <summary>Object does not support current locale setting.</summary>
    Friend Shared ReadOnly Property [ID447] As String
      Get
        Return GetResourceString("ID447", "Object does not support current locale setting.")
      End Get
    End Property
    ''' <summary>Named argument not found.</summary>
    Friend Shared ReadOnly Property [ID448] As String
      Get
        Return GetResourceString("ID448", "Named argument not found.")
      End Get
    End Property
    ''' <summary>Argument not optional.</summary>
    Friend Shared ReadOnly Property [ID449] As String
      Get
        Return GetResourceString("ID449", "Argument not optional.")
      End Get
    End Property
    ''' <summary>Wrong number of arguments or property assignment was not valid.</summary>
    Friend Shared ReadOnly Property [ID450] As String
      Get
        Return GetResourceString("ID450", "Wrong number of arguments or property assignment was not valid.")
      End Get
    End Property
    ''' <summary>Property let procedure not defined and property get procedure did not return an object.</summary>
    Friend Shared ReadOnly Property [ID451] As String
      Get
        Return GetResourceString("ID451", "Property let procedure not defined and property get procedure did not return an object.")
      End Get
    End Property
    ''' <summary>Ordinal is not valid.</summary>
    Friend Shared ReadOnly Property [ID452] As String
      Get
        Return GetResourceString("ID452", "Ordinal is not valid.")
      End Get
    End Property
    ''' <summary>Specified DLL function not found.</summary>
    Friend Shared ReadOnly Property [ID453] As String
      Get
        Return GetResourceString("ID453", "Specified DLL function not found.")
      End Get
    End Property
    ''' <summary>Code resource not found.</summary>
    Friend Shared ReadOnly Property [ID454] As String
      Get
        Return GetResourceString("ID454", "Code resource not found.")
      End Get
    End Property
    ''' <summary>Code resource lock error.</summary>
    Friend Shared ReadOnly Property [ID455] As String
      Get
        Return GetResourceString("ID455", "Code resource lock error.")
      End Get
    End Property
    ''' <summary>This key is already associated with an element of this collection.</summary>
    Friend Shared ReadOnly Property [ID457] As String
      Get
        Return GetResourceString("ID457", "This key is already associated with an element of this collection.")
      End Get
    End Property
    ''' <summary>Variable uses an Automation type not supported in Visual Basic.</summary>
    Friend Shared ReadOnly Property [ID458] As String
      Get
        Return GetResourceString("ID458", "Variable uses an Automation type not supported in Visual Basic.")
      End Get
    End Property
    ''' <summary>Object or class does not support the set of events.</summary>
    Friend Shared ReadOnly Property [ID459] As String
      Get
        Return GetResourceString("ID459", "Object or class does not support the set of events.")
      End Get
    End Property
    ''' <summary>Clipboard format is not valid.</summary>
    Friend Shared ReadOnly Property [ID460] As String
      Get
        Return GetResourceString("ID460", "Clipboard format is not valid.")
      End Get
    End Property
    ''' <summary>Method or data member not found.</summary>
    Friend Shared ReadOnly Property [ID461] As String
      Get
        Return GetResourceString("ID461", "Method or data member not found.")
      End Get
    End Property
    ''' <summary>The remote server machine does not exist or is unavailable.</summary>
    Friend Shared ReadOnly Property [ID462] As String
      Get
        Return GetResourceString("ID462", "The remote server machine does not exist or is unavailable.")
      End Get
    End Property
    ''' <summary>Class not registered on local machine.</summary>
    Friend Shared ReadOnly Property [ID463] As String
      Get
        Return GetResourceString("ID463", "Class not registered on local machine.")
      End Get
    End Property
    ''' <summary>Picture is not valid.</summary>
    Friend Shared ReadOnly Property [ID481] As String
      Get
        Return GetResourceString("ID481", "Picture is not valid.")
      End Get
    End Property
    ''' <summary>Printer error.</summary>
    Friend Shared ReadOnly Property [ID482] As String
      Get
        Return GetResourceString("ID482", "Printer error.")
      End Get
    End Property
    ''' <summary>Cannot save file to TEMP.</summary>
    Friend Shared ReadOnly Property [ID735] As String
      Get
        Return GetResourceString("ID735", "Cannot save file to TEMP.")
      End Get
    End Property
    ''' <summary>Search text not found.</summary>
    Friend Shared ReadOnly Property [ID744] As String
      Get
        Return GetResourceString("ID744", "Search text not found.")
      End Get
    End Property
    ''' <summary>Replacements too long.</summary>
    Friend Shared ReadOnly Property [ID746] As String
      Get
        Return GetResourceString("ID746", "Replacements too long.")
      End Get
    End Property
    ''' <summary>Stop statement encountered.</summary>
    Friend Shared ReadOnly Property [ID999] As String
      Get
        Return GetResourceString("ID999", "Stop statement encountered.")
      End Get
    End Property
    ''' <summary>Feature not yet implemented.</summary>
    Friend Shared ReadOnly Property [ID32768] As String
      Get
        Return GetResourceString("ID32768", "Feature not yet implemented.")
      End Get
    End Property
    ''' <summary>False</summary>
    Friend Shared ReadOnly Property [StringFalse] As String
      Get
        Return GetResourceString("StringFalse", "False")
      End Get
    End Property
    ''' <summary>True</summary>
    Friend Shared ReadOnly Property [StringTrue] As String
      Get
        Return GetResourceString("StringTrue", "True")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be greater or equal to zero.</summary>
    Friend Shared ReadOnly Property [Argument_GEZero1] As String
      Get
        Return GetResourceString("Argument_GEZero1", "Argument '{0}' must be greater or equal to zero.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be greater than zero.</summary>
    Friend Shared ReadOnly Property [Argument_GTZero1] As String
      Get
        Return GetResourceString("Argument_GTZero1", "Argument '{0}' must be greater than zero.")
      End Get
    End Property
    ''' <summary>Argument 'Conversion' is not valid.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidVbStrConv] As String
      Get
        Return GetResourceString("Argument_InvalidVbStrConv", "Argument 'Conversion' is not valid.")
      End Get
    End Property
    ''' <summary>VbStrConv.SimplifiedChinese and VbStrConv.TraditionalChinese cannot be combined.</summary>
    Friend Shared ReadOnly Property [Argument_StrConvSCandTC] As String
      Get
        Return GetResourceString("Argument_StrConvSCandTC", "VbStrConv.SimplifiedChinese and VbStrConv.TraditionalChinese cannot be combined.")
      End Get
    End Property
    ''' <summary>This system does not contain support for the Simplified Chinese locale.</summary>
    Friend Shared ReadOnly Property [Argument_SCNotSupported] As String
      Get
        Return GetResourceString("Argument_SCNotSupported", "This system does not contain support for the Simplified Chinese locale.")
      End Get
    End Property
    ''' <summary>This system does not contain support for the Traditional Chinese locale.</summary>
    Friend Shared ReadOnly Property [Argument_TCNotSupported] As String
      Get
        Return GetResourceString("Argument_TCNotSupported", "This system does not contain support for the Traditional Chinese locale.")
      End Get
    End Property
    ''' <summary>This system does not contain support for the Japanese locale.</summary>
    Friend Shared ReadOnly Property [Argument_JPNNotSupported] As String
      Get
        Return GetResourceString("Argument_JPNNotSupported", "This system does not contain support for the Japanese locale.")
      End Get
    End Property
    ''' <summary>VbStrConv.Wide and VbStrConv.Narrow cannot be combined.</summary>
    Friend Shared ReadOnly Property [Argument_IllegalWideNarrow] As String
      Get
        Return GetResourceString("Argument_IllegalWideNarrow", "VbStrConv.Wide and VbStrConv.Narrow cannot be combined.")
      End Get
    End Property
    ''' <summary>This system does not contain support for the Locale specified.</summary>
    Friend Shared ReadOnly Property [Argument_LocalNotSupported] As String
      Get
        Return GetResourceString("Argument_LocalNotSupported", "This system does not contain support for the Locale specified.")
      End Get
    End Property

    Friend Shared Function ProgressDialogUploadingLabel() As String
      Throw New NotImplementedException()
    End Function

    Friend Shared Function ProgressDialogUploadingTitle() As String
      Throw New NotImplementedException()
    End Function

    ''' <summary>VbStrConv.Wide and VbStrConv.Narrow are not applicable to the locale specified.</summary>
    Friend Shared ReadOnly Property [Argument_WideNarrowNotApplicable] As String
      Get
        Return GetResourceString("Argument_WideNarrowNotApplicable", "VbStrConv.Wide and VbStrConv.Narrow are not applicable to the locale specified.")
      End Get
    End Property
    ''' <summary>VbStrConv.Katakana and VbStrConv.Hiragana cannot be combined.</summary>
    Friend Shared ReadOnly Property [Argument_IllegalKataHira] As String
      Get
        Return GetResourceString("Argument_IllegalKataHira", "VbStrConv.Katakana and VbStrConv.Hiragana cannot be combined.")
      End Get
    End Property
    ''' <summary>Length of argument '{0}' must be greater than zero.</summary>
    Friend Shared ReadOnly Property [Argument_LengthGTZero1] As String
      Get
        Return GetResourceString("Argument_LengthGTZero1", "Length of argument '{0}' must be greater than zero.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be within the range of -32768 to 65535.</summary>
    Friend Shared ReadOnly Property [Argument_RangeTwoBytes1] As String
      Get
        Return GetResourceString("Argument_RangeTwoBytes1", "Argument '{0}' must be within the range of -32768 to 65535.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be greater than 0 or equal to -1.</summary>
    Friend Shared ReadOnly Property [Argument_MinusOneOrGTZero1] As String
      Get
        Return GetResourceString("Argument_MinusOneOrGTZero1", "Argument '{0}' must be greater than 0 or equal to -1.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be greater than or equal to -1.</summary>
    Friend Shared ReadOnly Property [Argument_GEMinusOne1] As String
      Get
        Return GetResourceString("Argument_GEMinusOne1", "Argument '{0}' must be greater than or equal to -1.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be greater than or equal to 1.</summary>
    Friend Shared ReadOnly Property [Argument_GEOne1] As String
      Get
        Return GetResourceString("Argument_GEOne1", "Argument '{0}' must be greater than or equal to 1.")
      End Get
    End Property
    ''' <summary>Argument '{0}' cannot be a multi-dimensional array.</summary>
    Friend Shared ReadOnly Property [Argument_RankEQOne1] As String
      Get
        Return GetResourceString("Argument_RankEQOne1", "Argument '{0}' cannot be a multi-dimensional array.")
      End Get
    End Property
    ''' <summary>Loop control variable of type '{1}' does not implement the 'System.IComparable' interface.</summary>
    Friend Shared ReadOnly Property [Argument_IComparable2] As String
      Get
        Return GetResourceString("Argument_IComparable2", "Loop control variable of type '{1}' does not implement the 'System.IComparable' interface.")
      End Get
    End Property
    ''' <summary>Type of argument '{0}' is '{1}', which is not numeric.</summary>
    Friend Shared ReadOnly Property [Argument_NotNumericType2] As String
      Get
        Return GetResourceString("Argument_NotNumericType2", "Type of argument '{0}' is '{1}', which is not numeric.")
      End Get
    End Property
    ''' <summary>Argument '{0}' is not a valid value.</summary>
    Public Shared ReadOnly Property [Argument_InvalidValue1] As String
      Get
        Return GetResourceString("Argument_InvalidValue1", "Argument '{0}' is not a valid value.")
      End Get
    End Property
    ''' <summary>Argument '{0}' cannot be converted to type '{1}'.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidValueType2] As String
      Get
        Return GetResourceString("Argument_InvalidValueType2", "Argument '{0}' cannot be converted to type '{1}'.")
      End Get
    End Property
    ''' <summary>Argument 'Path' is Nothing or empty.</summary>
    Friend Shared ReadOnly Property [Argument_PathNullOrEmpty] As String
      Get
        Return GetResourceString("Argument_PathNullOrEmpty", "Argument 'Path' is Nothing or empty.")
      End Get
    End Property
    ''' <summary>Argument '{0}' is Nothing or empty.</summary>
    Friend Shared ReadOnly Property [Argument_PathNullOrEmpty1] As String
      Get
        Return GetResourceString("Argument_PathNullOrEmpty1", "Argument '{0}' is Nothing or empty.")
      End Get
    End Property
    ''' <summary>Argument value '{0}' contains characters that are not valid in a path name.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidPathChars1] As String
      Get
        Return GetResourceString("Argument_InvalidPathChars1", "Argument value '{0}' contains characters that are not valid in a path name.")
      End Get
    End Property
    ''' <summary>Arguments are not valid.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidValue] As String
      Get
        Return GetResourceString("Argument_InvalidValue", "Arguments are not valid.")
      End Get
    End Property
    ''' <summary>'Before' and 'After' arguments cannot be combined.</summary>
    Friend Shared ReadOnly Property [Collection_BeforeAfterExclusive] As String
      Get
        Return GetResourceString("Collection_BeforeAfterExclusive", "'Before' and 'After' arguments cannot be combined.")
      End Get
    End Property
    ''' <summary>Add failed. Duplicate key value supplied.</summary>
    Friend Shared ReadOnly Property [Collection_DuplicateKey] As String
      Get
        Return GetResourceString("Collection_DuplicateKey", "Add failed. Duplicate key value supplied.")
      End Get
    End Property
    ''' <summary>Argument 'Access' is not valid. Valid values for Input mode are 'OpenAccess.Read' and 'OpenAccess.Default'.</summary>
    Friend Shared ReadOnly Property [FileSystem_IllegalInputAccess] As String
      Get
        Return GetResourceString("FileSystem_IllegalInputAccess", "Argument 'Access' is not valid. Valid values for Input mode are 'OpenAccess.Read' and 'OpenAccess.Default'.")
      End Get
    End Property
    ''' <summary>Argument 'Access' is not valid. Valid values for Output mode are 'OpenAccess.Write' and 'OpenAccess.Default'.</summary>
    Friend Shared ReadOnly Property [FileSystem_IllegalOutputAccess] As String
      Get
        Return GetResourceString("FileSystem_IllegalOutputAccess", "Argument 'Access' is not valid. Valid values for Output mode are 'OpenAccess.Write' and 'OpenAccess.Default'.")
      End Get
    End Property
    ''' <summary>Argument 'Access' is not valid. Valid values for Append mode are 'OpenAccess.Write' and 'OpenAccess.Default'.</summary>
    Friend Shared ReadOnly Property [FileSystem_IllegalAppendAccess] As String
      Get
        Return GetResourceString("FileSystem_IllegalAppendAccess", "Argument 'Access' is not valid. Valid values for Append mode are 'OpenAccess.Write' and 'OpenAccess.Default'.")
      End Get
    End Property
    ''' <summary>File '{0}' cannot be deleted because it is open.</summary>
    Friend Shared ReadOnly Property [FileSystem_FileAlreadyOpen1] As String
      Get
        Return GetResourceString("FileSystem_FileAlreadyOpen1", "File '{0}' cannot be deleted because it is open.")
      End Get
    End Property
    ''' <summary>Cannot convert start value of type '{0}' and step value of type '{1}' to a common numeric type.</summary>
    Friend Shared ReadOnly Property [ForLoop_CommonType2] As String
      Get
        Return GetResourceString("ForLoop_CommonType2", "Cannot convert start value of type '{0}' and step value of type '{1}' to a common numeric type.")
      End Get
    End Property
    ''' <summary>Cannot convert start value of type '{0}', limit value of type '{1}', and step value of type '{2}' to a common numeric type.</summary>
    Friend Shared ReadOnly Property [ForLoop_CommonType3] As String
      Get
        Return GetResourceString("ForLoop_CommonType3", "Cannot convert start value of type '{0}', limit value of type '{1}', and step value of type '{2}' to a common numeric type.")
      End Get
    End Property
    ''' <summary>Cannot convert argument '{0}' of type '{1}' to type '{2}'.</summary>
    Friend Shared ReadOnly Property [ForLoop_ConvertToType3] As String
      Get
        Return GetResourceString("ForLoop_ConvertToType3", "Cannot convert argument '{0}' of type '{1}' to type '{2}'.")
      End Get
    End Property
    ''' <summary>Type '{0}' must define an operator '{1}', with parameters of type '{0}', to be used in a 'For' statement.</summary>
    Friend Shared ReadOnly Property [ForLoop_OperatorRequired2] As String
      Get
        Return GetResourceString("ForLoop_OperatorRequired2", "Type '{0}' must define an operator '{1}', with parameters of type '{0}', to be used in a 'For' statement.")
      End Get
    End Property
    ''' <summary>Return and parameter types of '{0}' must be of type '{1}' to be used in a 'For' statement.</summary>
    Friend Shared ReadOnly Property [ForLoop_UnacceptableOperator2] As String
      Get
        Return GetResourceString("ForLoop_UnacceptableOperator2", "Return and parameter types of '{0}' must be of type '{1}' to be used in a 'For' statement.")
      End Get
    End Property
    ''' <summary>Parameter types of '{0}' must be of type '{1}' to be used in a 'For' statement.</summary>
    Friend Shared ReadOnly Property [ForLoop_UnacceptableRelOperator2] As String
      Get
        Return GetResourceString("ForLoop_UnacceptableRelOperator2", "Parameter types of '{0}' must be of type '{1}' to be used in a 'For' statement.")
      End Get
    End Property
    ''' <summary>Internal error in the Microsoft Visual Basic runtime.</summary>
    Friend Shared ReadOnly Property [InternalError_VisualBasicRuntime] As String
      Get
        Return GetResourceString("InternalError_VisualBasicRuntime", "Internal error in the Microsoft Visual Basic runtime.")
      End Get
    End Property
    ''' <summary>'Dir' function must first be called with a 'PathName' argument.</summary>
    Friend Shared ReadOnly Property [DIR_IllegalCall] As String
      Get
        Return GetResourceString("DIR_IllegalCall", "'Dir' function must first be called with a 'PathName' argument.")
      End Get
    End Property
    ''' <summary>No files found matching '{0}'.</summary>
    Friend Shared ReadOnly Property [KILL_NoFilesFound1] As String
      Get
        Return GetResourceString("KILL_NoFilesFound1", "No files found matching '{0}'.")
      End Get
    End Property
    ''' <summary>Error number must be within the range 0 to 65535.</summary>
    Friend Shared ReadOnly Property [MaxErrNumber] As String
      Get
        Return GetResourceString("MaxErrNumber", "Error number must be within the range 0 to 65535.")
      End Get
    End Property
    ''' <summary>Drive '{0}' not found.</summary>
    Friend Shared ReadOnly Property [FileSystem_DriveNotFound1] As String
      Get
        Return GetResourceString("FileSystem_DriveNotFound1", "Drive '{0}' not found.")
      End Get
    End Property
    ''' <summary>File '{0}' not found.</summary>
    Friend Shared ReadOnly Property [FileSystem_FileNotFound1] As String
      Get
        Return GetResourceString("FileSystem_FileNotFound1", "File '{0}' not found.")
      End Get
    End Property
    ''' <summary>Path '{0}' not found.</summary>
    Friend Shared ReadOnly Property [FileSystem_PathNotFound1] As String
      Get
        Return GetResourceString("FileSystem_PathNotFound1", "Path '{0}' not found.")
      End Get
    End Property
    ''' <summary>Division by zero.</summary>
    Friend Shared ReadOnly Property [Financial_CalcDivByZero] As String
      Get
        Return GetResourceString("Financial_CalcDivByZero", "Division by zero.")
      End Get
    End Property
    ''' <summary>Cannot calculate number of periods using the arguments provided.</summary>
    Friend Shared ReadOnly Property [Financial_CannotCalculateNPer] As String
      Get
        Return GetResourceString("Financial_CannotCalculateNPer", "Cannot calculate number of periods using the arguments provided.")
      End Get
    End Property
    ''' <summary>Cannot calculate rate using the arguments provided.</summary>
    Friend Shared ReadOnly Property [Financial_CannotCalculateRate] As String
      Get
        Return GetResourceString("Financial_CannotCalculateRate", "Cannot calculate rate using the arguments provided.")
      End Get
    End Property
    ''' <summary>Argument '{0}' is Nothing.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidNullValue1] As String
      Get
        Return GetResourceString("Argument_InvalidNullValue1", "Argument '{0}' is Nothing.")
      End Get
    End Property
    ''' <summary>Argument 'NPer' must be greater than zero.</summary>
    Friend Shared ReadOnly Property [Rate_NPerMustBeGTZero] As String
      Get
        Return GetResourceString("Rate_NPerMustBeGTZero", "Argument 'NPer' must be greater than zero.")
      End Get
    End Property
    ''' <summary>Argument 'Per' is not valid.</summary>
    Friend Shared ReadOnly Property [PPMT_PerGT0AndLTNPer] As String
      Get
        Return GetResourceString("PPMT_PerGT0AndLTNPer", "Argument 'Per' is not valid.")
      End Get
    End Property
    ''' <summary>Argument 'Life' cannot be zero.</summary>
    Friend Shared ReadOnly Property [Financial_LifeNEZero] As String
      Get
        Return GetResourceString("Financial_LifeNEZero", "Argument 'Life' cannot be zero.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be greater than or equal to zero.</summary>
    Friend Shared ReadOnly Property [Financial_ArgGEZero1] As String
      Get
        Return GetResourceString("Financial_ArgGEZero1", "Argument '{0}' must be greater than or equal to zero.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be greater than zero.</summary>
    Friend Shared ReadOnly Property [Financial_ArgGTZero1] As String
      Get
        Return GetResourceString("Financial_ArgGTZero1", "Argument '{0}' must be greater than zero.")
      End Get
    End Property
    ''' <summary>Argument 'Period' must be less than or equal to argument 'Life'.</summary>
    Friend Shared ReadOnly Property [Financial_PeriodLELife] As String
      Get
        Return GetResourceString("Financial_PeriodLELife", "Argument 'Period' must be less than or equal to argument 'Life'.")
      End Get
    End Property
    ''' <summary>Argument '{0}' is not valid for the array.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidRank1] As String
      Get
        Return GetResourceString("Argument_InvalidRank1", "Argument '{0}' is not valid for the array.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be within the range 1 to 255.</summary>
    Friend Shared ReadOnly Property [Argument_Range1toFF1] As String
      Get
        Return GetResourceString("Argument_Range1toFF1", "Argument '{0}' must be within the range 1 to 255.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be within the range 0 to 99.</summary>
    Friend Shared ReadOnly Property [Argument_Range0to99_1] As String
      Get
        Return GetResourceString("Argument_Range0to99_1", "Argument '{0}' must be within the range 0 to 99.")
      End Get
    End Property
    ''' <summary>Registry key '{0}' could not be created.</summary>
    Friend Shared ReadOnly Property [Interaction_ResKeyNotCreated1] As String
      Get
        Return GetResourceString("Interaction_ResKeyNotCreated1", "Registry key '{0}' could not be created.")
      End Get
    End Property
    ''' <summary>Locale id '{0}' is not supported on this system.</summary>
    Friend Shared ReadOnly Property [Argument_LCIDNotSupported1] As String
      Get
        Return GetResourceString("Argument_LCIDNotSupported1", "Locale id '{0}' is not supported on this system.")
      End Get
    End Property
    ''' <summary>Conversion from type '{0}' to type '{1}' is not valid.</summary>
    Friend Shared ReadOnly Property [InvalidCast_FromTo] As String
      Get
        Return GetResourceString("InvalidCast_FromTo", "Conversion from type '{0}' to type '{1}' is not valid.")
      End Get
    End Property
    ''' <summary>Conversion from string "{0}" to type '{1}' is not valid.</summary>
    Friend Shared ReadOnly Property [InvalidCast_FromStringTo] As String
      Get
        Return GetResourceString("InvalidCast_FromStringTo", "Conversion from string ""{0}"" to type '{1}' is not valid.")
      End Get
    End Property
    ''' <summary>Insufficient security permissions to set the system date.</summary>
    Friend Shared ReadOnly Property [SetLocalDateFailure] As String
      Get
        Return GetResourceString("SetLocalDateFailure", "Insufficient security permissions to set the system date.")
      End Get
    End Property
    ''' <summary>Insufficient security permissions to set the system time.</summary>
    Friend Shared ReadOnly Property [SetLocalTimeFailure] As String
      Get
        Return GetResourceString("SetLocalTimeFailure", "Insufficient security permissions to set the system time.")
      End Get
    End Property
    ''' <summary>File I/O of a structure with field '{0}' of type '{1}' is not valid.</summary>
    Friend Shared ReadOnly Property [Argument_UnsupportedFieldType2] As String
      Get
        Return GetResourceString("Argument_UnsupportedFieldType2", "File I/O of a structure with field '{0}' of type '{1}' is not valid.")
      End Get
    End Property
    ''' <summary>File I/O with type '{0}' is not valid.</summary>
    Friend Shared ReadOnly Property [Argument_UnsupportedIOType1] As String
      Get
        Return GetResourceString("Argument_UnsupportedIOType1", "File I/O with type '{0}' is not valid.")
      End Get
    End Property
    ''' <summary>Argument '{0}' cannot be converted to type 'Date'.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidDateValue1] As String
      Get
        Return GetResourceString("Argument_InvalidDateValue1", "Argument '{0}' cannot be converted to type 'Date'.")
      End Get
    End Property
    ''' <summary>Use 'FilePutObject' instead of 'FilePut' when using argument of type 'Object'.</summary>
    Friend Shared ReadOnly Property [UseFilePutObject] As String
      Get
        Return GetResourceString("UseFilePutObject", "Use 'FilePutObject' instead of 'FilePut' when using argument of type 'Object'.")
      End Get
    End Property
    ''' <summary>Argument '{0}' cannot be converted to a numeric value.</summary>
    Friend Shared ReadOnly Property [ArgumentNotNumeric1] As String
      Get
        Return GetResourceString("ArgumentNotNumeric1", "Argument '{0}' cannot be converted to a numeric value.")
      End Get
    End Property
    ''' <summary>String length exceeds maximum length of 32767 characters for 'FileSystem' APIs.</summary>
    Friend Shared ReadOnly Property [FileIO_StringLengthExceeded] As String
      Get
        Return GetResourceString("FileIO_StringLengthExceeded", "String length exceeds maximum length of 32767 characters for 'FileSystem' APIs.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be less than or equal to the length of argument '{1}'.</summary>
    Friend Shared ReadOnly Property [Argument_IndexLELength2] As String
      Get
        Return GetResourceString("Argument_IndexLELength2", "Argument '{0}' must be less than or equal to the length of argument '{1}'.")
      End Get
    End Property
    ''' <summary>No default member found for type '{0}'.</summary>
    Friend Shared ReadOnly Property [MissingMember_NoDefaultMemberFound1] As String
      Get
        Return GetResourceString("MissingMember_NoDefaultMemberFound1", "No default member found for type '{0}'.")
      End Get
    End Property
    ''' <summary>Public member '{0}' on type '{1}' not found.</summary>
    Friend Shared ReadOnly Property [MissingMember_MemberNotFoundOnType2] As String
      Get
        Return GetResourceString("MissingMember_MemberNotFoundOnType2", "Public member '{0}' on type '{1}' not found.")
      End Get
    End Property
    ''' <summary>Public Set '{0}' on type '{1}' not found.  Use 'CallByName' function with 'CallType.Let'.</summary>
    Friend Shared ReadOnly Property [MissingMember_MemberSetNotFoundOnType2] As String
      Get
        Return GetResourceString("MissingMember_MemberSetNotFoundOnType2", "Public Set '{0}' on type '{1}' not found.  Use 'CallByName' function with 'CallType.Let'.")
      End Get
    End Property
    ''' <summary>Public Let '{0}' on type '{1}' not found.  Use 'CallByName' function with 'CallType.Set'.</summary>
    Friend Shared ReadOnly Property [MissingMember_MemberLetNotFoundOnType2] As String
      Get
        Return GetResourceString("MissingMember_MemberLetNotFoundOnType2", "Public Let '{0}' on type '{1}' not found.  Use 'CallByName' function with 'CallType.Set'.")
      End Get
    End Property
    ''' <summary>Invocation of '{0}' on type '{1}' returned Nothing.</summary>
    Friend Shared ReadOnly Property [IntermediateLateBoundNothingResult1] As String
      Get
        Return GetResourceString("IntermediateLateBoundNothingResult1", "Invocation of '{0}' on type '{1}' returned Nothing.")
      End Get
    End Property
    ''' <summary>Yes;Yes;No</summary>
    Friend Shared ReadOnly Property [YesNoFormatStyle] As String
      Get
        Return GetResourceString("YesNoFormatStyle", "Yes;Yes;No")
      End Get
    End Property
    ''' <summary>On;On;Off</summary>
    Friend Shared ReadOnly Property [OnOffFormatStyle] As String
      Get
        Return GetResourceString("OnOffFormatStyle", "On;On;Off")
      End Get
    End Property
    ''' <summary>True;True;False</summary>
    Friend Shared ReadOnly Property [TrueFalseFormatStyle] As String
      Get
        Return GetResourceString("TrueFalseFormatStyle", "True;True;False")
      End Get
    End Property
    ''' <summary>Collection index must be in the range 1 to the size of the collection.</summary>
    Friend Shared ReadOnly Property [Argument_CollectionIndex] As String
      Get
        Return GetResourceString("Argument_CollectionIndex", "Collection index must be in the range 1 to the size of the collection.")
      End Get
    End Property
    ''' <summary>Method '{1}' has no parameter named '{0}'.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidNamedArg2] As String
      Get
        Return GetResourceString("Argument_InvalidNamedArg2", "Method '{1}' has no parameter named '{0}'.")
      End Get
    End Property
    ''' <summary>Method '{0}' cannot be called with {1} argument(s).</summary>
    Friend Shared ReadOnly Property [NoMethodTakingXArguments2] As String
      Get
        Return GetResourceString("NoMethodTakingXArguments2", "Method '{0}' cannot be called with {1} argument(s).")
      End Get
    End Property
    ''' <summary>Named argument '{0}' specified multiple times.</summary>
    Friend Shared ReadOnly Property [NamedArgumentAlreadyUsed1] As String
      Get
        Return GetResourceString("NamedArgumentAlreadyUsed1", "Named argument '{0}' specified multiple times.")
      End Get
    End Property
    ''' <summary>Named arguments cannot match ParamArray parameters.</summary>
    Friend Shared ReadOnly Property [NamedArgumentOnParamArray] As String
      Get
        Return GetResourceString("NamedArgumentOnParamArray", "Named arguments cannot match ParamArray parameters.")
      End Get
    End Property
    ''' <summary>'StrConv.LinguisticCasing' requires 'StrConv.Lowercase' or 'StrConv.Uppercase'.</summary>
    Friend Shared ReadOnly Property [LinguisticRequirements] As String
      Get
        Return GetResourceString("LinguisticRequirements", "'StrConv.LinguisticCasing' requires 'StrConv.Lowercase' or 'StrConv.Uppercase'.")
      End Get
    End Property
    ''' <summary>Cannot determine array type because it is Nothing.</summary>
    Friend Shared ReadOnly Property [Argument_ArrayNotInitialized] As String
      Get
        Return GetResourceString("Argument_ArrayNotInitialized", "Cannot determine array type because it is Nothing.")
      End Get
    End Property
    ''' <summary>Late-bound assignment to a field of value type '{0}' is not valid when '{1}' is the result of a late-bound expression.</summary>
    Friend Shared ReadOnly Property [RValueBaseForValueType] As String
      Get
        Return GetResourceString("RValueBaseForValueType", "Late-bound assignment to a field of value type '{0}' is not valid when '{1}' is the result of a late-bound expression.")
      End Get
    End Property
    ''' <summary>Argument {1} to method '{0}' has type '{2}' and cannot be converted to '{3}'.</summary>
    Friend Shared ReadOnly Property [InvalidCast_FromToArg4] As String
      Get
        Return GetResourceString("InvalidCast_FromToArg4", "Argument {1} to method '{0}' has type '{2}' and cannot be converted to '{3}'.")
      End Get
    End Property
    ''' <summary>Array dimensions do not match those specified by the 'VBFixedArray' attribute.</summary>
    Friend Shared ReadOnly Property [Argument_ArrayDimensionsDontMatch] As String
      Get
        Return GetResourceString("Argument_ArrayDimensionsDontMatch", "Array dimensions do not match those specified by the 'VBFixedArray' attribute.")
      End Get
    End Property
    ''' <summary>Expression '{0}' is not a procedure, but occurs as the target of a procedure call.</summary>
    Friend Shared ReadOnly Property [ExpressionNotProcedure] As String
      Get
        Return GetResourceString("ExpressionNotProcedure", "Expression '{0}' is not a procedure, but occurs as the target of a procedure call.")
      End Get
    End Property
    ''' <summary>No accessible overloaded '{0}' is most specific for these arguments: {1}</summary>
    Friend Shared ReadOnly Property [AmbiguousCall_ExactMatch2] As String
      Get
        Return GetResourceString("AmbiguousCall_ExactMatch2", "No accessible overloaded '{0}' is most specific for these arguments: {1}")
      End Get
    End Property
    ''' <summary>No accessible overloaded '{0}' can be called with these arguments without a narrowing conversion: {1}</summary>
    Friend Shared ReadOnly Property [AmbiguousCall2] As String
      Get
        Return GetResourceString("AmbiguousCall2", "No accessible overloaded '{0}' can be called with these arguments without a narrowing conversion: {1}")
      End Get
    End Property
    ''' <summary>No accessible overloaded '{0}' can be called with these arguments without a widening conversion: {1}</summary>
    Friend Shared ReadOnly Property [AmbiguousCall_WideningConversion2] As String
      Get
        Return GetResourceString("AmbiguousCall_WideningConversion2", "No accessible overloaded '{0}' can be called with these arguments without a widening conversion: {1}")
      End Get
    End Property
    ''' <summary>No accessible overloaded '{0}' can be called without a narrowing conversion.</summary>
    Friend Shared ReadOnly Property [AmbiguousMatch_NarrowingConversion1] As String
      Get
        Return GetResourceString("AmbiguousMatch_NarrowingConversion1", "No accessible overloaded '{0}' can be called without a narrowing conversion.")
      End Get
    End Property
    ''' <summary>Managed classes derived from a COM class cannot be called late bound.</summary>
    Friend Shared ReadOnly Property [LateboundCallToInheritedComClass] As String
      Get
        Return GetResourceString("LateboundCallToInheritedComClass", "Managed classes derived from a COM class cannot be called late bound.")
      End Get
    End Property
    ''' <summary>Field '{0}' of type '{1}' is 'ReadOnly'.</summary>
    Friend Shared ReadOnly Property [MissingMember_ReadOnlyField2] As String
      Get
        Return GetResourceString("MissingMember_ReadOnlyField2", "Field '{0}' of type '{1}' is 'ReadOnly'.")
      End Get
    End Property
    ''' <summary>Arguments to 'VBFixedArrayAttribute' are not valid.</summary>
    Friend Shared ReadOnly Property [Invalid_VBFixedArray] As String
      Get
        Return GetResourceString("Invalid_VBFixedArray", "Arguments to 'VBFixedArrayAttribute' are not valid.")
      End Get
    End Property
    ''' <summary>Arguments to 'VBFixedStringAttribute' are not valid.</summary>
    Friend Shared ReadOnly Property [Invalid_VBFixedString] As String
      Get
        Return GetResourceString("Invalid_VBFixedString", "Arguments to 'VBFixedStringAttribute' are not valid.")
      End Get
    End Property
    ''' <summary>Array argument cannot have more than 2 dimensions.</summary>
    Friend Shared ReadOnly Property [Argument_UnsupportedArrayDimensions] As String
      Get
        Return GetResourceString("Argument_UnsupportedArrayDimensions", "Array argument cannot have more than 2 dimensions.")
      End Get
    End Property
    ''' <summary>Length of fixed length string cannot be zero.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidFixedLengthString] As String
      Get
        Return GetResourceString("Argument_InvalidFixedLengthString", "Length of fixed length string cannot be zero.")
      End Get
    End Property
    ''' <summary>Named arguments are not valid as array subscripts.</summary>
    Friend Shared ReadOnly Property [Argument_InvalidNamedArgs] As String
      Get
        Return GetResourceString("Argument_InvalidNamedArgs", "Named arguments are not valid as array subscripts.")
      End Get
    End Property
    ''' <summary>'{0}' is a type in '{1}' and cannot be used as an expression.</summary>
    Friend Shared ReadOnly Property [Argument_IllegalNestedType2] As String
      Get
        Return GetResourceString("Argument_IllegalNestedType2", "'{0}' is a type in '{1}' and cannot be used as an expression.")
      End Get
    End Property
    ''' <summary>'FilePutObject' of structure '{0}' is not valid.</summary>
    Friend Shared ReadOnly Property [Argument_PutObjectOfValueType1] As String
      Get
        Return GetResourceString("Argument_PutObjectOfValueType1", "'FilePutObject' of structure '{0}' is not valid.")
      End Get
    End Property
    ''' <summary>'SyncLock' operand cannot be of type '{0}' because '{0}' is not a reference type.</summary>
    Friend Shared ReadOnly Property [SyncLockRequiresReferenceType1] As String
      Get
        Return GetResourceString("SyncLockRequiresReferenceType1", "'SyncLock' operand cannot be of type '{0}' because '{0}' is not a reference type.")
      End Get
    End Property
    ''' <summary>File is not opened for read access.</summary>
    Friend Shared ReadOnly Property [FileOpenedNoRead] As String
      Get
        Return GetResourceString("FileOpenedNoRead", "File is not opened for read access.")
      End Get
    End Property
    ''' <summary>File is not opened for write access.</summary>
    Friend Shared ReadOnly Property [FileOpenedNoWrite] As String
      Get
        Return GetResourceString("FileOpenedNoWrite", "File is not opened for write access.")
      End Get
    End Property
    ''' <summary>Reference to non-shared member '{0}' requires an object reference.</summary>
    Friend Shared ReadOnly Property [NullReference_InstanceReqToAccessMember1] As String
      Get
        Return GetResourceString("NullReference_InstanceReqToAccessMember1", "Reference to non-shared member '{0}' requires an object reference.")
      End Get
    End Property
    ''' <summary>Late bound calls to file system methods in the Visual Basic runtime are not permitted.</summary>
    Friend Shared ReadOnly Property [Security_LateBoundCallsNotPermitted] As String
      Get
        Return GetResourceString("Security_LateBoundCallsNotPermitted", "Late bound calls to file system methods in the Visual Basic runtime are not permitted.")
      End Get
    End Property
    ''' <summary>Method invocation failed because '{0}' cannot be called with these arguments:{1}</summary>
    Friend Shared ReadOnly Property [MatchArgumentFailure2] As String
      Get
        Return GetResourceString("MatchArgumentFailure2", "Method invocation failed because '{0}' cannot be called with these arguments:{1}")
      End Get
    End Property
    ''' <summary>Property '{0}' is WriteOnly.</summary>
    Friend Shared ReadOnly Property [NoGetProperty1] As String
      Get
        Return GetResourceString("NoGetProperty1", "Property '{0}' is WriteOnly.")
      End Get
    End Property
    ''' <summary>Property '{0}' is ReadOnly.</summary>
    Friend Shared ReadOnly Property [NoSetProperty1] As String
      Get
        Return GetResourceString("NoSetProperty1", "Property '{0}' is ReadOnly.")
      End Get
    End Property
    ''' <summary>Method '{0}' cannot be the target of an assignment.</summary>
    Friend Shared ReadOnly Property [MethodAssignment1] As String
      Get
        Return GetResourceString("MethodAssignment1", "Method '{0}' cannot be the target of an assignment.")
      End Get
    End Property
    ''' <summary>Overload resolution failed because no '{0}' is Public.</summary>
    Friend Shared ReadOnly Property [NoViableOverloadCandidates1] As String
      Get
        Return GetResourceString("NoViableOverloadCandidates1", "Overload resolution failed because no '{0}' is Public.")
      End Get
    End Property
    ''' <summary>Overload resolution failed because no accessible '{0}' accepts this number of arguments.</summary>
    Friend Shared ReadOnly Property [NoArgumentCountOverloadCandidates1] As String
      Get
        Return GetResourceString("NoArgumentCountOverloadCandidates1", "Overload resolution failed because no accessible '{0}' accepts this number of arguments.")
      End Get
    End Property
    ''' <summary>Overload resolution failed because no accessible '{0}' accepts this number of type arguments.</summary>
    Friend Shared ReadOnly Property [NoTypeArgumentCountOverloadCandidates1] As String
      Get
        Return GetResourceString("NoTypeArgumentCountOverloadCandidates1", "Overload resolution failed because no accessible '{0}' accepts this number of type arguments.")
      End Get
    End Property
    ''' <summary>Overload resolution failed because no Public '{0}' can be called with these arguments:{1}</summary>
    Friend Shared ReadOnly Property [NoCallableOverloadCandidates2] As String
      Get
        Return GetResourceString("NoCallableOverloadCandidates2", "Overload resolution failed because no Public '{0}' can be called with these arguments:{1}")
      End Get
    End Property
    ''' <summary>Overload resolution failed because no Public '{0}' can be called without a narrowing conversion:{1}</summary>
    Friend Shared ReadOnly Property [NoNonNarrowingOverloadCandidates2] As String
      Get
        Return GetResourceString("NoNonNarrowingOverloadCandidates2", "Overload resolution failed because no Public '{0}' can be called without a narrowing conversion:{1}")
      End Get
    End Property
    ''' <summary>Overload resolution failed because no Public '{0}' is most specific for these arguments:{1}</summary>
    Friend Shared ReadOnly Property [NoMostSpecificOverload2] As String
      Get
        Return GetResourceString("NoMostSpecificOverload2", "Overload resolution failed because no Public '{0}' is most specific for these arguments:{1}")
      End Get
    End Property
    ''' <summary>Conversion from type '{0}' to type '{1}' is ambiguous.</summary>
    Friend Shared ReadOnly Property [AmbiguousCast2] As String
      Get
        Return GetResourceString("AmbiguousCast2", "Conversion from type '{0}' to type '{1}' is ambiguous.")
      End Get
    End Property
    ''' <summary>Not most specific.</summary>
    Friend Shared ReadOnly Property [NotMostSpecificOverload] As String
      Get
        Return GetResourceString("NotMostSpecificOverload", "Not most specific.")
      End Get
    End Property
    ''' <summary>Named argument '{0}' matches no parameter of '{1}'.</summary>
    Friend Shared ReadOnly Property [NamedParamNotFound2] As String
      Get
        Return GetResourceString("NamedParamNotFound2", "Named argument '{0}' matches no parameter of '{1}'.")
      End Get
    End Property
    ''' <summary>Named argument '{0}' cannot match a ParamArray parameter.</summary>
    Friend Shared ReadOnly Property [NamedParamArrayArgument1] As String
      Get
        Return GetResourceString("NamedParamArrayArgument1", "Named argument '{0}' cannot match a ParamArray parameter.")
      End Get
    End Property
    ''' <summary>Parameter '{0}' of '{1}' already has a matching argument.</summary>
    Friend Shared ReadOnly Property [NamedArgUsedTwice2] As String
      Get
        Return GetResourceString("NamedArgUsedTwice2", "Parameter '{0}' of '{1}' already has a matching argument.")
      End Get
    End Property
    ''' <summary>Argument not specified for parameter '{0}'.</summary>
    Friend Shared ReadOnly Property [OmittedArgument1] As String
      Get
        Return GetResourceString("OmittedArgument1", "Argument not specified for parameter '{0}'.")
      End Get
    End Property
    ''' <summary>Omitted argument cannot match a ParamArray parameter.</summary>
    Friend Shared ReadOnly Property [OmittedParamArrayArgument] As String
      Get
        Return GetResourceString("OmittedParamArrayArgument", "Omitted argument cannot match a ParamArray parameter.")
      End Get
    End Property
    ''' <summary>Argument matching parameter '{0}' cannot convert from '{1}' to '{2}'.</summary>
    Friend Shared ReadOnly Property [ArgumentMismatch3] As String
      Get
        Return GetResourceString("ArgumentMismatch3", "Argument matching parameter '{0}' cannot convert from '{1}' to '{2}'.")
      End Get
    End Property
    ''' <summary>Argument matching parameter '{0}' cannot convert from '{1}' to '{2}' because the conversion is ambiguous.</summary>
    Friend Shared ReadOnly Property [ArgumentMismatchAmbiguous3] As String
      Get
        Return GetResourceString("ArgumentMismatchAmbiguous3", "Argument matching parameter '{0}' cannot convert from '{1}' to '{2}' because the conversion is ambiguous.")
      End Get
    End Property
    ''' <summary>Argument matching parameter '{0}' narrows from '{1}' to '{2}'.</summary>
    Friend Shared ReadOnly Property [ArgumentNarrowing3] As String
      Get
        Return GetResourceString("ArgumentNarrowing3", "Argument matching parameter '{0}' narrows from '{1}' to '{2}'.")
      End Get
    End Property
    ''' <summary>ByRef parameter '{0}' cannot convert from '{1}' to '{2}' when assigning back to the matching argument.</summary>
    Friend Shared ReadOnly Property [ArgumentMismatchCopyBack3] As String
      Get
        Return GetResourceString("ArgumentMismatchCopyBack3", "ByRef parameter '{0}' cannot convert from '{1}' to '{2}' when assigning back to the matching argument.")
      End Get
    End Property
    ''' <summary>ByRef parameter '{0}' cannot convert from '{1}' to '{2}' when assigning back to the matching argument because the conversion is ambiguous.</summary>
    Friend Shared ReadOnly Property [ArgumentMismatchAmbiguousCopyBack3] As String
      Get
        Return GetResourceString("ArgumentMismatchAmbiguousCopyBack3", "ByRef parameter '{0}' cannot convert from '{1}' to '{2}' when assigning back to the matching argument because the conversion is ambiguous.")
      End Get
    End Property
    ''' <summary>ByRef parameter '{0}' narrows from '{1}' to '{2}' when assigning back to the matching argument.</summary>
    Friend Shared ReadOnly Property [ArgumentNarrowingCopyBack3] As String
      Get
        Return GetResourceString("ArgumentNarrowingCopyBack3", "ByRef parameter '{0}' narrows from '{1}' to '{2}' when assigning back to the matching argument.")
      End Get
    End Property
    ''' <summary>Type parameter '{0}' cannot be determined.</summary>
    Friend Shared ReadOnly Property [UnboundTypeParam1] As String
      Get
        Return GetResourceString("UnboundTypeParam1", "Type parameter '{0}' cannot be determined.")
      End Get
    End Property
    ''' <summary>Type argument inference fails for argument matching parameter '{0}'.</summary>
    Friend Shared ReadOnly Property [TypeInferenceFails1] As String
      Get
        Return GetResourceString("TypeInferenceFails1", "Type argument inference fails for argument matching parameter '{0}'.")
      End Get
    End Property
    ''' <summary>Substitution of type arguments failed.</summary>
    Friend Shared ReadOnly Property [FailedTypeArgumentBinding] As String
      Get
        Return GetResourceString("FailedTypeArgumentBinding", "Substitution of type arguments failed.")
      End Get
    End Property
    ''' <summary>Operator is not defined for type '{0}'.</summary>
    Friend Shared ReadOnly Property [NoValidOperator_OneOperand] As String
      Get
        Return GetResourceString("NoValidOperator_OneOperand", "Operator is not defined for type '{0}'.")
      End Get
    End Property
    ''' <summary>Operator is not defined for {0} and {1}.</summary>
    Friend Shared ReadOnly Property [NoValidOperator_TwoOperands] As String
      Get
        Return GetResourceString("NoValidOperator_TwoOperands", "Operator is not defined for {0} and {1}.")
      End Get
    End Property
    ''' <summary>Operator '{0}' is not defined for type '{1}'.</summary>
    Friend Shared ReadOnly Property [UnaryOperand2] As String
      Get
        Return GetResourceString("UnaryOperand2", "Operator '{0}' is not defined for type '{1}'.")
      End Get
    End Property
    ''' <summary>Operator '{0}' is not defined for {1} and {2}.</summary>
    Friend Shared ReadOnly Property [BinaryOperands3] As String
      Get
        Return GetResourceString("BinaryOperands3", "Operator '{0}' is not defined for {1} and {2}.")
      End Get
    End Property
    ''' <summary>string "{0}"</summary>
    Friend Shared ReadOnly Property [NoValidOperator_StringType1] As String
      Get
        Return GetResourceString("NoValidOperator_StringType1", "string ""{0}""")
      End Get
    End Property
    ''' <summary>type '{0}'</summary>
    Friend Shared ReadOnly Property [NoValidOperator_NonStringType1] As String
      Get
        Return GetResourceString("NoValidOperator_NonStringType1", "type '{0}'")
      End Get
    End Property
    ''' <summary>Call to set property '{0}' requires at least one argument.</summary>
    Friend Shared ReadOnly Property [PropertySetMissingArgument1] As String
      Get
        Return GetResourceString("PropertySetMissingArgument1", "Call to set property '{0}' requires at least one argument.")
      End Get
    End Property
    ''' <summary>Empty placeholder to adjust for 1-based array.</summary>
    Friend Shared ReadOnly Property [EmptyPlaceHolderMessage] As String
      Get
        Return GetResourceString("EmptyPlaceHolderMessage", "Empty placeholder to adjust for 1-based array.")
      End Get
    End Property
    ''' <summary>Could not find special directory '{0}'.</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectoryNotExist] As String
      Get
        Return GetResourceString("IO_SpecialDirectoryNotExist", "Could not find special directory '{0}'.")
      End Get
    End Property
    ''' <summary>My Documents</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectory_MyDocuments] As String
      Get
        Return GetResourceString("IO_SpecialDirectory_MyDocuments", "My Documents")
      End Get
    End Property
    ''' <summary>My Music</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectory_MyMusic] As String
      Get
        Return GetResourceString("IO_SpecialDirectory_MyMusic", "My Music")
      End Get
    End Property
    ''' <summary>My Pictures</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectory_MyPictures] As String
      Get
        Return GetResourceString("IO_SpecialDirectory_MyPictures", "My Pictures")
      End Get
    End Property
    ''' <summary>Desktop</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectory_Desktop] As String
      Get
        Return GetResourceString("IO_SpecialDirectory_Desktop", "Desktop")
      End Get
    End Property
    ''' <summary>Programs</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectory_Programs] As String
      Get
        Return GetResourceString("IO_SpecialDirectory_Programs", "Programs")
      End Get
    End Property
    ''' <summary>Program Files</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectory_ProgramFiles] As String
      Get
        Return GetResourceString("IO_SpecialDirectory_ProgramFiles", "Program Files")
      End Get
    End Property
    ''' <summary>Temporary directory</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectory_Temp] As String
      Get
        Return GetResourceString("IO_SpecialDirectory_Temp", "Temporary directory")
      End Get
    End Property
    ''' <summary>All users' application data</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectory_AllUserAppData] As String
      Get
        Return GetResourceString("IO_SpecialDirectory_AllUserAppData", "All users' application data")
      End Get
    End Property
    ''' <summary>Current user's application data</summary>
    Friend Shared ReadOnly Property [IO_SpecialDirectory_UserAppData] As String
      Get
        Return GetResourceString("IO_SpecialDirectory_UserAppData", "Current user's application data")
      End Get
    End Property
    ''' <summary>Could not complete operation since a file already exists in this path '{0}'.</summary>
    Friend Shared ReadOnly Property [IO_FileExists_Path] As String
      Get
        Return GetResourceString("IO_FileExists_Path", "Could not complete operation since a file already exists in this path '{0}'.")
      End Get
    End Property
    ''' <summary>Could not find file '{0}'.</summary>
    Friend Shared ReadOnly Property [IO_FileNotFound_Path] As String
      Get
        Return GetResourceString("IO_FileNotFound_Path", "Could not find file '{0}'.")
      End Get
    End Property
    ''' <summary>Could not complete operation since a directory already exists in this path '{0}'.</summary>
    Friend Shared ReadOnly Property [IO_DirectoryExists_Path] As String
      Get
        Return GetResourceString("IO_DirectoryExists_Path", "Could not complete operation since a directory already exists in this path '{0}'.")
      End Get
    End Property
    ''' <summary>Could not complete operation since directory is a root directory: '{0}'.</summary>
    Friend Shared ReadOnly Property [IO_DirectoryIsRoot_Path] As String
      Get
        Return GetResourceString("IO_DirectoryIsRoot_Path", "Could not complete operation since directory is a root directory: '{0}'.")
      End Get
    End Property
    ''' <summary>Could not find directory '{0}'.</summary>
    Friend Shared ReadOnly Property [IO_DirectoryNotFound_Path] As String
      Get
        Return GetResourceString("IO_DirectoryNotFound_Path", "Could not find directory '{0}'.")
      End Get
    End Property
    ''' <summary>Could not get parent path since the given path is a root directory: '{0}'.</summary>
    Friend Shared ReadOnly Property [IO_GetParentPathIsRoot_Path] As String
      Get
        Return GetResourceString("IO_GetParentPathIsRoot_Path", "Could not get parent path since the given path is a root directory: '{0}'.")
      End Get
    End Property
    ''' <summary>Argument '{0}' must be a name, and not a relative or absolute path: '{1}'.</summary>
    Friend Shared ReadOnly Property [IO_ArgumentIsPath_Name_Path] As String
      Get
        Return GetResourceString("IO_ArgumentIsPath_Name_Path", "Argument '{0}' must be a name, and not a relative or absolute path: '{1}'.")
      End Get
    End Property
    ''' <summary>Could not complete operation on some files and directories. See the Data property of the exception for more details.</summary>
    Friend Shared ReadOnly Property [IO_CopyMoveRecursive] As String
      Get
        Return GetResourceString("IO_CopyMoveRecursive", "Could not complete operation on some files and directories. See the Data property of the exception for more details.")
      End Get
    End Property
    ''' <summary>Could not complete operation since target directory is under source directory.</summary>
    Friend Shared ReadOnly Property [IO_CyclicOperation] As String
      Get
        Return GetResourceString("IO_CyclicOperation", "Could not complete operation since target directory is under source directory.")
      End Get
    End Property
    ''' <summary>Could not complete operation since source directory and target directory are the same.</summary>
    Friend Shared ReadOnly Property [IO_SourceEqualsTargetDirectory] As String
      Get
        Return GetResourceString("IO_SourceEqualsTargetDirectory", "Could not complete operation since source directory and target directory are the same.")
      End Get
    End Property
    ''' <summary>One of the wildcards is Nothing or empty string.</summary>
    Friend Shared ReadOnly Property [IO_GetFiles_NullPattern] As String
      Get
        Return GetResourceString("IO_GetFiles_NullPattern", "One of the wildcards is Nothing or empty string.")
      End Get
    End Property
    ''' <summary>The given path is a Win32 device path. Don't use paths starting with '\\.\'.</summary>
    Friend Shared ReadOnly Property [IO_DevicePath] As String
      Get
        Return GetResourceString("IO_DevicePath", "The given path is a Win32 device path. Don't use paths starting with '\\.\'.")
      End Get
    End Property
    ''' <summary>The given file path ends with a directory separator character.</summary>
    Friend Shared ReadOnly Property [IO_FilePathException] As String
      Get
        Return GetResourceString("IO_FilePathException", "The given file path ends with a directory separator character.")
      End Get
    End Property
    ''' <summary>Argument cannot be Nothing.</summary>
    Friend Shared ReadOnly Property [General_ArgumentNullException] As String
      Get
        Return GetResourceString("General_ArgumentNullException", "Argument cannot be Nothing.")
      End Get
    End Property
    ''' <summary>Argument '{0}' cannot be an empty string or Nothing.</summary>
    Friend Shared ReadOnly Property [General_ArgumentEmptyOrNothing_Name] As String
      Get
        Return GetResourceString("General_ArgumentEmptyOrNothing_Name", "Argument '{0}' cannot be an empty string or Nothing.")
      End Get
    End Property
    ''' <summary>NumberOfChars must be greater than zero.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_NumberOfCharsMustBePositive] As String
      Get
        Return GetResourceString("TextFieldParser_NumberOfCharsMustBePositive", "NumberOfChars must be greater than zero.")
      End Get
    End Property
    ''' <summary>The stream passed to TextFieldParser cannot be read.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_StreamNotReadable] As String
      Get
        Return GetResourceString("TextFieldParser_StreamNotReadable", "The stream passed to TextFieldParser cannot be read.")
      End Get
    End Property
    ''' <summary>TextFieldParser is unable to complete the read operation because maximum buffer size has been exceeded.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_BufferExceededMaxSize] As String
      Get
        Return GetResourceString("TextFieldParser_BufferExceededMaxSize", "TextFieldParser is unable to complete the read operation because maximum buffer size has been exceeded.")
      End Get
    End Property
    ''' <summary>Line {0} cannot be parsed using the current Delimiters.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_MalFormedDelimitedLine] As String
      Get
        Return GetResourceString("TextFieldParser_MalFormedDelimitedLine", "Line {0} cannot be parsed using the current Delimiters.")
      End Get
    End Property
    ''' <summary>Line {0} cannot be parsed using the current FieldWidths.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_MalFormedFixedWidthLine] As String
      Get
        Return GetResourceString("TextFieldParser_MalFormedFixedWidthLine", "Line {0} cannot be parsed using the current FieldWidths.")
      End Get
    End Property
    ''' <summary>Line {0} cannot be read because it exceeds the maximum line size.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_MaxLineSizeExceeded] As String
      Get
        Return GetResourceString("TextFieldParser_MaxLineSizeExceeded", "Line {0} cannot be read because it exceeds the maximum line size.")
      End Get
    End Property
    ''' <summary>Unable to read fixed width fields because FieldWidths is Nothing or empty.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_FieldWidthsNothing] As String
      Get
        Return GetResourceString("TextFieldParser_FieldWidthsNothing", "Unable to read fixed width fields because FieldWidths is Nothing or empty.")
      End Get
    End Property
    ''' <summary>Unable to read delimited fields because Delimiters is Nothing or empty.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_DelimitersNothing] As String
      Get
        Return GetResourceString("TextFieldParser_DelimitersNothing", "Unable to read delimited fields because Delimiters is Nothing or empty.")
      End Get
    End Property
    ''' <summary>All field widths, except the last element, must be greater than zero. A field width less than or equal to zero in the last element indicates the last field is of variable length.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_FieldWidthsMustPositive] As String
      Get
        Return GetResourceString("TextFieldParser_FieldWidthsMustPositive", "All field widths, except the last element, must be greater than zero. A field width less than or equal to zero in the last element indicates the last field is of variable length.")
      End Get
    End Property
    ''' <summary>Unable to read delimited fields because a double quote is not a legal delimiter when HasFieldsEnclosedInQuotes is set to True.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_IllegalDelimiter] As String
      Get
        Return GetResourceString("TextFieldParser_IllegalDelimiter", "Unable to read delimited fields because a double quote is not a legal delimiter when HasFieldsEnclosedInQuotes is set to True.")
      End Get
    End Property
    ''' <summary>A delimiter cannot be Nothing or an empty String.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_DelimiterNothing] As String
      Get
        Return GetResourceString("TextFieldParser_DelimiterNothing", "A delimiter cannot be Nothing or an empty String.")
      End Get
    End Property
    ''' <summary>A double quote is not a valid comment token for delimited fields where HasFieldsEnclosedInQuotes is set to True.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_InvalidComment] As String
      Get
        Return GetResourceString("TextFieldParser_InvalidComment", "A double quote is not a valid comment token for delimited fields where HasFieldsEnclosedInQuotes is set to True.")
      End Get
    End Property
    ''' <summary>Line Number:{0}</summary>
    Friend Shared ReadOnly Property [TextFieldParser_MalformedExtraData] As String
      Get
        Return GetResourceString("TextFieldParser_MalformedExtraData", "Line Number:{0}")
      End Get
    End Property
    ''' <summary>TextFieldParser does not support comment tokens that contain white space.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_WhitespaceInToken] As String
      Get
        Return GetResourceString("TextFieldParser_WhitespaceInToken", "TextFieldParser does not support comment tokens that contain white space.")
      End Get
    End Property
    ''' <summary>TextFieldParser does not support delimiters that contain end-of-line characters.</summary>
    Friend Shared ReadOnly Property [TextFieldParser_EndCharsInDelimiter] As String
      Get
        Return GetResourceString("TextFieldParser_EndCharsInDelimiter", "TextFieldParser does not support delimiters that contain end-of-line characters.")
      End Get
    End Property
    ''' <summary>UI not available for copy or move</summary>
    Friend Shared ReadOnly Property [NoShellCopyOrMove] As String
      Get
        Return GetResourceString("NoShellCopyOrMove", "UI not available for copy or move")
      End Get
    End Property
    ''' <summary>Method requires System.Windows.Forms.</summary>
    Friend Shared ReadOnly Property [MethodRequiresSystemWindowsForms] As String
      Get
        Return GetResourceString("MethodRequiresSystemWindowsForms", "Method requires System.Windows.Forms.")
      End Get
    End Property

    Friend Shared ReadOnly Property ApplicationLog_FileExceedsMaximumSize As String
      Get
        Return GetResourceString("ApplicationLog_FileExceedsMaximumSize", Nothing)
      End Get
    End Property

    Friend Shared ReadOnly Property ApplicationLog_ReservedSpaceEncroached As String
      Get
        Return GetResourceString("ApplicationLog_ReservedSpaceEncroached", Nothing)
      End Get
    End Property

    Public Shared ReadOnly Property ApplicationLog_FreeSpaceError As String
      Get
        Return GetResourceString("ApplicationLog_FreeSpaceError", Nothing)
      End Get
    End Property

    Public Shared ReadOnly Property DiagnosticInfo_Memory As String
      Get
        Return GetResourceString("DiagnosticInfo_Memory", Nothing)
      End Get
    End Property

    Public Shared ReadOnly Property Network_DownloadNeedsFilename As String
      Get
        Return GetResourceString("Network_DownloadNeedsFilename", Nothing)
      End Get
    End Property

    Public Shared ReadOnly Property Network_InvalidUriString As String
      Get
        Return GetResourceString("Network_InvalidUriString", Nothing)
      End Get
    End Property

    Public Shared ReadOnly Property Network_NetworkNotAvailable As String
      Get
        Return GetResourceString("Network_NetworkNotAvailable", Nothing)
      End Get
    End Property

    Public Shared ReadOnly Property Network_UploadAddressNeedsFilename As String
      Get
        Return GetResourceString("Network_UploadAddressNeedsFilename", Nothing)
      End Get
    End Property

    Public Shared ReadOnly Property Mouse_NoWheelIsPresent As String
      Get
        Return GetResourceString("Mouse_NoWheelIsPresent", Nothing)
      End Get
    End Property

  End Class

End Namespace